<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Silahkan Pilih --                _9f24ad</name>
   <tag></tag>
   <elementGuidId>e162d39c-c70b-48d5-ab5d-97e4f822cca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='registerReferralId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#registerReferralId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>11696ec5-d2b6-4836-917e-4c18b9a50795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerReferralId</value>
      <webElementGuid>fabceb95-0530-4b0a-9f90-04de671c6abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registerReferralId</value>
      <webElementGuid>6a061e49-c77b-4ae7-ad41-de6d112ae393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0c9cbd01-c0ce-4257-870b-56e9fe7dc5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                </value>
      <webElementGuid>12b3446f-e84f-4198-9378-4180dad73460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerReferralId&quot;)</value>
      <webElementGuid>6c22df4a-0bb3-4536-884a-7c954794c562</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='registerReferralId']</value>
      <webElementGuid>75484e21-a553-400d-9fb2-daf641a9d751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[7]/select</value>
      <webElementGuid>73f18abf-578d-4886-83bf-2adb11280aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana Kamu tahu ALAMI? (Opsional)'])[1]/following::select[1]</value>
      <webElementGuid>e16f2234-387b-4b37-843a-b19827790e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Referral (Opsional)'])[1]/following::select[1]</value>
      <webElementGuid>4252ba64-0537-4aa4-8c22-b20b6acf0b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan'])[1]/preceding::select[1]</value>
      <webElementGuid>9d1a1573-df7e-413e-917e-e1bf749eb431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar disini'])[1]/preceding::select[1]</value>
      <webElementGuid>78e68a3d-4f3a-4499-9b69-a16cf39d0292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f25c8943-c6e0-4ab5-9fbe-461ac886fe71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'registerReferralId' and @name = 'registerReferralId' and (text() = '
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                ' or . = '
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                ')]</value>
      <webElementGuid>afe39e8e-bb6c-4d52-b99c-4d2b803dfff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
